Atomic bridge
movemntdev/aptos-core pull request #72
Opened 2024-09-24 19:14 UTC by andyjsbell

## Description

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

## Key Areas to Review

## Checklist
- [ ] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I identified and added all stakeholders and component owners affected by this change as reviewers
- [ ] I tested both happy and unhappy path of the functionality
- [ ] I have made corresponding changes to the documentation

2024-09-25 21:10 UTC, andygolay commented on aptos-move/framework/aptos-framework/sources/atomic_bridge.move
> +        block::initialize_for_test(aptos_framework, 1);
Since we're using timestamp, `block::initialize_for_test` is probably not needed. Tests pass without it.

2024-09-25 21:11 UTC, andygolay requested changes
- Move unit tests and Move Prover verification pass. Still looking into the details of both to ensure soundness.

- Reviewing against auditor feedback:

  - Time lock verification for `atomic_bridge_counterparty::complete_bridge_transfer` [(HAL-11)](https://github.com/movementlabsxyz/movement/issues/568): 

We have `complete_bridge_transfer` calling `bridge_store::complete_transfer` which calls `complete_details` that checks the validity and correctness of the hash lock as well as that the state is pending. But I don't see it checking the time lock with something along the lines of:

```
assert!(timestamp::now_seconds() <= bridge_transfer.time_lock, ETIMELOCK_EXPIRED);
```
Recommendation: add this check into `complete_details` with other completion checks.

  - Regarding use of block height vs timestamp, which was an auditor issue, you are handling that fully with timestamp. Added one comment about block.

2024-09-25 21:12 UTC, andygolay commented on aptos-move/framework/aptos-framework/sources/atomic_bridge.move
> +        assert_correct_hash_lock(details, hash_lock);
Add time lock verification here?

2024-09-26 14:05 UTC, andyjsbell commented
Test and coverage, I believe @franck44 will be looking further into the specification side of thing.  I will also look at the spec again as this was my first bash at it. 

@andygolay you may find this interesting for the e2e work you have been exploring which is part of this PR.
https://github.com/movementlabsxyz/aptos-core/blob/d76b853b019491ff8cd3b3cf85fbc96963051aa3/aptos-move/e2e-move-tests/src/tests/bridge.rs#L35

Some coverage results.  

```
Module 0000000000000000000000000000000000000000000000000000000000000001::ethereum
>>> % Module coverage: 100.00
Module 0000000000000000000000000000000000000000000000000000000000000001::atomic_bridge_store
>>> % Module coverage: 92.40
Module 0000000000000000000000000000000000000000000000000000000000000001::atomic_bridge_configuration
>>> % Module coverage: 95.45
Module 0000000000000000000000000000000000000000000000000000000000000001::atomic_bridge
>>> % Module coverage: 81.82
Module 0000000000000000000000000000000000000000000000000000000000000001::atomic_bridge_counterparty
>>> % Module coverage: 100.00
Module 0000000000000000000000000000000000000000000000000000000000000001::atomic_bridge_initiator
>>> % Module coverage: 100.00

```

Would be great to get CI up and running as the e2e tests were broken, some time soon :)

2024-09-26 14:17 UTC, andygolay submitted a review, later dismissed

2024-09-26 14:23 UTC, andygolay commented
LGTM for testnet iteration.

2024-09-26 14:36 UTC, andygolay commented
Added issue here for CI implementation https://github.com/movementlabsxyz/aptos-core/issues/73

2024-09-26 15:05 UTC, andyjsbell commented
> LGTM for testnet iteration. Looking into the E2E tests more deeply now, thanks for highlighting those.
No worries.  I think we would want to see this on devnet first though.  I have purposely added [DO NOT MERGE] to the PR for the time being as I think its best to feature flag this before merging

2024-09-26 15:42 UTC, andygolay commented
Yep, devnet then testnet + feature flag makes good sense.

2024-09-30 19:24 UTC, 0xmovses approved these changes
LGTM

2024-09-30 19:51 UTC, andygolay approved these changes
LGTM

2024-09-30 19:53 UTC, merged